// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	domain "github.com/shanewolff/go-rest/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// AuthService is an autogenerated mock type for the AuthService type
type AuthService struct {
	mock.Mock
}

type AuthService_Expecter struct {
	mock *mock.Mock
}

func (_m *AuthService) EXPECT() *AuthService_Expecter {
	return &AuthService_Expecter{mock: &_m.Mock}
}

// Login provides a mock function with given fields: req
func (_m *AuthService) Login(req domain.LoginRequest) (string, *domain.User, error) {
	ret := _m.Called(req)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 string
	var r1 *domain.User
	var r2 error
	if rf, ok := ret.Get(0).(func(domain.LoginRequest) (string, *domain.User, error)); ok {
		return rf(req)
	}
	if rf, ok := ret.Get(0).(func(domain.LoginRequest) string); ok {
		r0 = rf(req)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(domain.LoginRequest) *domain.User); ok {
		r1 = rf(req)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*domain.User)
		}
	}

	if rf, ok := ret.Get(2).(func(domain.LoginRequest) error); ok {
		r2 = rf(req)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// AuthService_Login_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Login'
type AuthService_Login_Call struct {
	*mock.Call
}

// Login is a helper method to define mock.On call
//   - req domain.LoginRequest
func (_e *AuthService_Expecter) Login(req interface{}) *AuthService_Login_Call {
	return &AuthService_Login_Call{Call: _e.mock.On("Login", req)}
}

func (_c *AuthService_Login_Call) Run(run func(req domain.LoginRequest)) *AuthService_Login_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(domain.LoginRequest))
	})
	return _c
}

func (_c *AuthService_Login_Call) Return(_a0 string, _a1 *domain.User, _a2 error) *AuthService_Login_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *AuthService_Login_Call) RunAndReturn(run func(domain.LoginRequest) (string, *domain.User, error)) *AuthService_Login_Call {
	_c.Call.Return(run)
	return _c
}

// Register provides a mock function with given fields: req
func (_m *AuthService) Register(req domain.RegisterRequest) (*domain.User, error) {
	ret := _m.Called(req)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 *domain.User
	var r1 error
	if rf, ok := ret.Get(0).(func(domain.RegisterRequest) (*domain.User, error)); ok {
		return rf(req)
	}
	if rf, ok := ret.Get(0).(func(domain.RegisterRequest) *domain.User); ok {
		r0 = rf(req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}

	if rf, ok := ret.Get(1).(func(domain.RegisterRequest) error); ok {
		r1 = rf(req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AuthService_Register_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Register'
type AuthService_Register_Call struct {
	*mock.Call
}

// Register is a helper method to define mock.On call
//   - req domain.RegisterRequest
func (_e *AuthService_Expecter) Register(req interface{}) *AuthService_Register_Call {
	return &AuthService_Register_Call{Call: _e.mock.On("Register", req)}
}

func (_c *AuthService_Register_Call) Run(run func(req domain.RegisterRequest)) *AuthService_Register_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(domain.RegisterRequest))
	})
	return _c
}

func (_c *AuthService_Register_Call) Return(_a0 *domain.User, _a1 error) *AuthService_Register_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AuthService_Register_Call) RunAndReturn(run func(domain.RegisterRequest) (*domain.User, error)) *AuthService_Register_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateToken provides a mock function with given fields: tokenString
func (_m *AuthService) ValidateToken(tokenString string) (uint, error) {
	ret := _m.Called(tokenString)

	if len(ret) == 0 {
		panic("no return value specified for ValidateToken")
	}

	var r0 uint
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (uint, error)); ok {
		return rf(tokenString)
	}
	if rf, ok := ret.Get(0).(func(string) uint); ok {
		r0 = rf(tokenString)
	} else {
		r0 = ret.Get(0).(uint)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(tokenString)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AuthService_ValidateToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateToken'
type AuthService_ValidateToken_Call struct {
	*mock.Call
}

// ValidateToken is a helper method to define mock.On call
//   - tokenString string
func (_e *AuthService_Expecter) ValidateToken(tokenString interface{}) *AuthService_ValidateToken_Call {
	return &AuthService_ValidateToken_Call{Call: _e.mock.On("ValidateToken", tokenString)}
}

func (_c *AuthService_ValidateToken_Call) Run(run func(tokenString string)) *AuthService_ValidateToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *AuthService_ValidateToken_Call) Return(_a0 uint, _a1 error) *AuthService_ValidateToken_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AuthService_ValidateToken_Call) RunAndReturn(run func(string) (uint, error)) *AuthService_ValidateToken_Call {
	_c.Call.Return(run)
	return _c
}

// NewAuthService creates a new instance of AuthService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuthService(t interface {
	mock.TestingT
	Cleanup(func())
}) *AuthService {
	mock := &AuthService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
