// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	domain "github.com/shanewolff/go-rest/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// ItemService is an autogenerated mock type for the ItemService type
type ItemService struct {
	mock.Mock
}

type ItemService_Expecter struct {
	mock *mock.Mock
}

func (_m *ItemService) EXPECT() *ItemService_Expecter {
	return &ItemService_Expecter{mock: &_m.Mock}
}

// CreateItem provides a mock function with given fields: req
func (_m *ItemService) CreateItem(req domain.CreateItemRequest) (*domain.Item, error) {
	ret := _m.Called(req)

	if len(ret) == 0 {
		panic("no return value specified for CreateItem")
	}

	var r0 *domain.Item
	var r1 error
	if rf, ok := ret.Get(0).(func(domain.CreateItemRequest) (*domain.Item, error)); ok {
		return rf(req)
	}
	if rf, ok := ret.Get(0).(func(domain.CreateItemRequest) *domain.Item); ok {
		r0 = rf(req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Item)
		}
	}

	if rf, ok := ret.Get(1).(func(domain.CreateItemRequest) error); ok {
		r1 = rf(req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ItemService_CreateItem_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateItem'
type ItemService_CreateItem_Call struct {
	*mock.Call
}

// CreateItem is a helper method to define mock.On call
//   - req domain.CreateItemRequest
func (_e *ItemService_Expecter) CreateItem(req interface{}) *ItemService_CreateItem_Call {
	return &ItemService_CreateItem_Call{Call: _e.mock.On("CreateItem", req)}
}

func (_c *ItemService_CreateItem_Call) Run(run func(req domain.CreateItemRequest)) *ItemService_CreateItem_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(domain.CreateItemRequest))
	})
	return _c
}

func (_c *ItemService_CreateItem_Call) Return(_a0 *domain.Item, _a1 error) *ItemService_CreateItem_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ItemService_CreateItem_Call) RunAndReturn(run func(domain.CreateItemRequest) (*domain.Item, error)) *ItemService_CreateItem_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteItem provides a mock function with given fields: id
func (_m *ItemService) DeleteItem(id uint) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteItem")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uint) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ItemService_DeleteItem_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteItem'
type ItemService_DeleteItem_Call struct {
	*mock.Call
}

// DeleteItem is a helper method to define mock.On call
//   - id uint
func (_e *ItemService_Expecter) DeleteItem(id interface{}) *ItemService_DeleteItem_Call {
	return &ItemService_DeleteItem_Call{Call: _e.mock.On("DeleteItem", id)}
}

func (_c *ItemService_DeleteItem_Call) Run(run func(id uint)) *ItemService_DeleteItem_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uint))
	})
	return _c
}

func (_c *ItemService_DeleteItem_Call) Return(_a0 error) *ItemService_DeleteItem_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ItemService_DeleteItem_Call) RunAndReturn(run func(uint) error) *ItemService_DeleteItem_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllItems provides a mock function with no fields
func (_m *ItemService) GetAllItems() ([]domain.Item, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAllItems")
	}

	var r0 []domain.Item
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]domain.Item, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []domain.Item); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Item)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ItemService_GetAllItems_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllItems'
type ItemService_GetAllItems_Call struct {
	*mock.Call
}

// GetAllItems is a helper method to define mock.On call
func (_e *ItemService_Expecter) GetAllItems() *ItemService_GetAllItems_Call {
	return &ItemService_GetAllItems_Call{Call: _e.mock.On("GetAllItems")}
}

func (_c *ItemService_GetAllItems_Call) Run(run func()) *ItemService_GetAllItems_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ItemService_GetAllItems_Call) Return(_a0 []domain.Item, _a1 error) *ItemService_GetAllItems_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ItemService_GetAllItems_Call) RunAndReturn(run func() ([]domain.Item, error)) *ItemService_GetAllItems_Call {
	_c.Call.Return(run)
	return _c
}

// GetItem provides a mock function with given fields: id
func (_m *ItemService) GetItem(id uint) (*domain.Item, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetItem")
	}

	var r0 *domain.Item
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) (*domain.Item, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(uint) *domain.Item); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Item)
		}
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ItemService_GetItem_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetItem'
type ItemService_GetItem_Call struct {
	*mock.Call
}

// GetItem is a helper method to define mock.On call
//   - id uint
func (_e *ItemService_Expecter) GetItem(id interface{}) *ItemService_GetItem_Call {
	return &ItemService_GetItem_Call{Call: _e.mock.On("GetItem", id)}
}

func (_c *ItemService_GetItem_Call) Run(run func(id uint)) *ItemService_GetItem_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uint))
	})
	return _c
}

func (_c *ItemService_GetItem_Call) Return(_a0 *domain.Item, _a1 error) *ItemService_GetItem_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ItemService_GetItem_Call) RunAndReturn(run func(uint) (*domain.Item, error)) *ItemService_GetItem_Call {
	_c.Call.Return(run)
	return _c
}

// NewItemService creates a new instance of ItemService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewItemService(t interface {
	mock.TestingT
	Cleanup(func())
}) *ItemService {
	mock := &ItemService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
