// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	domain "github.com/shanewolff/go-rest/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// ItemRepository is an autogenerated mock type for the ItemRepository type
type ItemRepository struct {
	mock.Mock
}

type ItemRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *ItemRepository) EXPECT() *ItemRepository_Expecter {
	return &ItemRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: item
func (_m *ItemRepository) Create(item *domain.Item) error {
	ret := _m.Called(item)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*domain.Item) error); ok {
		r0 = rf(item)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ItemRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type ItemRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - item *domain.Item
func (_e *ItemRepository_Expecter) Create(item interface{}) *ItemRepository_Create_Call {
	return &ItemRepository_Create_Call{Call: _e.mock.On("Create", item)}
}

func (_c *ItemRepository_Create_Call) Run(run func(item *domain.Item)) *ItemRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*domain.Item))
	})
	return _c
}

func (_c *ItemRepository_Create_Call) Return(_a0 error) *ItemRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ItemRepository_Create_Call) RunAndReturn(run func(*domain.Item) error) *ItemRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: id
func (_m *ItemRepository) Delete(id uint) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uint) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ItemRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type ItemRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - id uint
func (_e *ItemRepository_Expecter) Delete(id interface{}) *ItemRepository_Delete_Call {
	return &ItemRepository_Delete_Call{Call: _e.mock.On("Delete", id)}
}

func (_c *ItemRepository_Delete_Call) Run(run func(id uint)) *ItemRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uint))
	})
	return _c
}

func (_c *ItemRepository_Delete_Call) Return(_a0 error) *ItemRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ItemRepository_Delete_Call) RunAndReturn(run func(uint) error) *ItemRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetAll provides a mock function with no fields
func (_m *ItemRepository) GetAll() ([]domain.Item, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []domain.Item
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]domain.Item, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []domain.Item); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Item)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ItemRepository_GetAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAll'
type ItemRepository_GetAll_Call struct {
	*mock.Call
}

// GetAll is a helper method to define mock.On call
func (_e *ItemRepository_Expecter) GetAll() *ItemRepository_GetAll_Call {
	return &ItemRepository_GetAll_Call{Call: _e.mock.On("GetAll")}
}

func (_c *ItemRepository_GetAll_Call) Run(run func()) *ItemRepository_GetAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ItemRepository_GetAll_Call) Return(_a0 []domain.Item, _a1 error) *ItemRepository_GetAll_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ItemRepository_GetAll_Call) RunAndReturn(run func() ([]domain.Item, error)) *ItemRepository_GetAll_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: id
func (_m *ItemRepository) GetByID(id uint) (*domain.Item, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *domain.Item
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) (*domain.Item, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(uint) *domain.Item); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Item)
		}
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ItemRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type ItemRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - id uint
func (_e *ItemRepository_Expecter) GetByID(id interface{}) *ItemRepository_GetByID_Call {
	return &ItemRepository_GetByID_Call{Call: _e.mock.On("GetByID", id)}
}

func (_c *ItemRepository_GetByID_Call) Run(run func(id uint)) *ItemRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uint))
	})
	return _c
}

func (_c *ItemRepository_GetByID_Call) Return(_a0 *domain.Item, _a1 error) *ItemRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ItemRepository_GetByID_Call) RunAndReturn(run func(uint) (*domain.Item, error)) *ItemRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// NewItemRepository creates a new instance of ItemRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewItemRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *ItemRepository {
	mock := &ItemRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
